# IMA Utils nuget pipeline

# Author: Anthony Brenelière

# Design time variables requirement:
# nugetFeeds : name of the nuget repository used for restore and for pushing empacked package
# buildConfiguration : Debug / Release / or other conf defined in your project

resources:
- repo: self

queue:
  name: PIC POOL

variables:
  projectDir: PromConfigClient
  projectPattern: '**/*PromConfigClient.csproj'
  testPattern: 'Tests/TestPromConfigClient/TestPromConfigClient.csproj'
  nugetFeeds: IMAProtectFeeds
  buildConfiguration: Release

trigger:

  branches:
    include:
    - master

  paths:
    include:
    - PromConfigClient/*   # <= does not work with variables 25/10/18

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(projectPattern)
    feedRestore: $(nugetFeeds)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(projectPattern)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test 
    projects: $(testPattern)
    arguments: '--configuration $(buildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: $(projectPattern)     # le projet de test est inclu car contient les handlers http de test
    include-symbols : true
    no-build: true

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: push
    feedPublish: $(nugetFeeds)
